### ISSUE TITLE
播放页顶部空间过大

### ISSUE THREAD

**Issue by ADP-P-P** [solstice23/refined-now-playing-netease#10]
![图片](https://user-images.githubusercontent.com/61774301/210525929-6265de9e-f524-48f0-8edf-f8f56437d372.png)
`如图所示，播放页元素下沉严重，顶部空白突兀`
是否可以添加顶部空白调节

**Comment by solstice23** [comment]
![image](https://user-images.githubusercontent.com/23134847/211213314-0c98f36a-7857-423d-87f7-d0580f394a92.png)
