### ISSUE TITLE
[Bug] 进度条贴底

### ISSUE THREAD

**Issue by 961739124** [solstice23/refined-now-playing-netease#102]
开启进度条贴底后，前1/3段进度条无法点击或拖动。鼠标移上，进度条变粗，但不是最粗的。
![capture_20230308185224875](https://user-images.githubusercontent.com/100020034/223694769-cbc03b3e-a757-4f94-82e2-5dfeb651853b.jpg)
在后2/3段可以正常点击进度条，触发进度条拖动后可以拖动到前1/3段。鼠标移上，进度条变为最粗的。

**Comment by q310550690** [comment]
确实有这问题

**Comment by 961739124** [comment]
还是没解决这个问题
