### ISSUE TITLE
进度条贴底的bug还是存在

### ISSUE THREAD

**Issue by 961739124** [solstice23/refined-now-playing-netease#104]
https://github.com/solstice23/refined-now-playing-netease/issues/102

**Comment by solstice23** [comment]
![image](https://user-images.githubusercontent.com/23134847/224539545-51a5be08-7de1-480b-8783-90a110d42a56.png)
![image](https://user-images.githubusercontent.com/23134847/224539538-390e7fd7-8aa6-41b9-a8d2-13d95422aa7e.png)

**Comment by 961739124** [comment]
> 


https://user-images.githubusercontent.com/100020034/224542780-3f35ca76-45b9-4385-96c8-464a14156b75.mp4

**Comment by solstice23** [comment]
F12x选中这个元素截图看看
![image](https://user-images.githubusercontent.com/23134847/224557063-4f9a24e9-e982-4e50-9725-b56c6febfc88.png)

**Comment by 961739124** [comment]
> 
![capture_20230313090753791](https://user-images.githubusercontent.com/100020034/224586493-be64e9c5-e48f-4e67-9905-4cec90e3baa1.jpg)

**Comment by solstice23** [comment]
![image](https://user-images.githubusercontent.com/23134847/224637121-d30049c3-a55a-4468-b64f-e1e2ee8e8d72.png)
点一下这个选择再截图
