### ISSUE TITLE
[功能建议] 增加歌词字体字重调节

### ISSUE THREAD

**Issue by itsCheney** [solstice23/refined-now-playing-netease#105]
苹方的细体在Windows上表现并不好，很多英文歌词显示出来没有AppleMusic那样美观，能否增加一个字重调节的选项？

**Comment by solstice23** [comment]
![image](https://user-images.githubusercontent.com/23134847/224921730-08a14caf-8cdb-4101-b400-6172116b43ed.png)

PingFang SC SemiBold

**Comment by itsCheney** [comment]
> ![image](https://user-images.githubusercontent.com/23134847/224921730-08a14caf-8cdb-4101-b400-6172116b43ed.png)
> 
> PingFang SC SemiBold

好的，非常感谢
