### ISSUE TITLE
最新版本更新完很多歌歌词只跟随第一句，然后就不动了

### ISSUE THREAD

**Issue by 33333365548468** [solstice23/refined-now-playing-netease#109]
![image](https://user-images.githubusercontent.com/53327162/226489213-ed55ea20-3a1e-46fe-9e98-21db5dab9190.png)

**Comment by solstice23** [comment]
是否使用了 LibFrontendPlay 相关插件

**Comment by 33333365548468** [comment]
> 是否使用了 LibFrontendPlay 相关插件

是的，删掉那个就解决了
