### ISSUE TITLE
字体看起来偏小

### ISSUE THREAD

**Issue by LJY7812** [solstice23/refined-now-playing-netease#11]
可否添加一个字体大小调节功能

**Comment by LJY7812** [comment]
![image](https://user-images.githubusercontent.com/103030400/211128099-5855769c-c068-4b93-8713-95643c4463d3.png)

**Comment by solstice23** [comment]
https://github.com/solstice23/refined-now-playing-netease/commit/26e4f2b5c07adf6238311a0a85ada80de33f0511
