### ISSUE TITLE
[BUG]右下角不明方块

### ISSUE THREAD

**Issue by NULL204** [solstice23/refined-now-playing-netease#113]
![image](https://user-images.githubusercontent.com/69097698/227749841-e335c2c2-54a1-489d-8705-ff64db76f13a.png)
在进入歌曲详细页时会有几率触发这里右下角的圆角方块，不知道是啥，点一下会进入播放歌单
![image](https://user-images.githubusercontent.com/69097698/227749890-31e1cf78-5978-41e2-9252-a797d992591f.png)

**Comment by solstice23** [comment]
![image](https://user-images.githubusercontent.com/23134847/228248699-c1107361-4f53-402a-a113-d918d60bce7c.png)
