### ISSUE TITLE
所有歌曲歌词无法显示

### ISSUE THREAD

**Issue by JackScofield** [solstice23/refined-now-playing-netease#116]
插件版本 2.16.0
BetterNCM 1.1.0
网易云版本 2.10.7
系统 win10
安装插件以后所有歌曲的歌词无法显示，歌曲封面，评论，作者， 专辑，设置按钮，下方控制栏均正常显示。

![issue](https://user-images.githubusercontent.com/37141563/227806758-c93bd46d-a29c-40e3-b576-930e916aa419.png)

**Comment by solstice23** [comment]
重启网易云
