### ISSUE TITLE
歌词现在都不显示词曲作者了吗

### ISSUE THREAD

**Issue by ChengzZg** [solstice23/refined-now-playing-netease#117]
想看词曲作者但是都不显示了，但是好像有些歌能显示，不清楚原理

**Comment by solstice23** [comment]
词曲作者吗？我加一下，现在用的歌词源词曲作者是独立的
加在最下面可以吗

**Comment by ChengzZg** [comment]
好好好，加在开头吧，习惯点

**Comment by solstice23** [comment]
加在开头独占几行占用歌词位置，改成小字又别扭，还是加底部吧 （

**Comment by solstice23** [comment]
![image](https://user-images.githubusercontent.com/23134847/228248791-c727e516-5021-4d1f-a11b-78ac90a2ab24.png)
