### ISSUE TITLE
[BUG]在安装material-you-theme-netease与refined-now-playing-netease时，进入详细界面时，material-you-theme-netease发生短暂失效

### ISSUE THREAD

**Issue by NULL204** [solstice23/refined-now-playing-netease#122]
如标题以及视频所示

https://user-images.githubusercontent.com/69097698/228595845-9f8823ec-0335-440e-b94f-092432589484.mp4

**Comment by solstice23** [comment]
![image](https://user-images.githubusercontent.com/23134847/228613207-19cdea4c-cb6b-440c-821b-7164927bcef8.png)
关闭
