### ISSUE TITLE
音量调节滑块鼠标悬停问题

### ISSUE THREAD

**Issue by Grindashit** [solstice23/refined-now-playing-netease#125]
进入播放页后选择调节音量，在弹出调节滑块后鼠标悬于滑块上时滑块消失，调节不了音量，不是很了解这方面的知识，是否是hover设置的问题？

https://user-images.githubusercontent.com/103481717/229338153-b6e334cc-b640-4c33-8747-e94d1b7912e4.mp4

**Comment by Grindashit** [comment]
https://user-images.githubusercontent.com/103481717/229338199-fe57c96f-f8aa-4d1a-8b70-c6804a78e559.mp4

**Comment by Grindashit** [comment]
https://user-images.githubusercontent.com/103481717/229338368-2a3581da-ccd8-47f7-8f69-6c6495cd4b5e.mp4

**Comment by solstice23** [comment]
是否使用了 MD You 主题

**Comment by Grindashit** [comment]
> 是否使用了 MD You 主题

是的，用了Material You主题，删除插件后问题消失了，感谢！
