### ISSUE TITLE
16:10分辨率错位问题

### ISSUE THREAD

**Issue by Colorfuldiamond** [solstice23/refined-now-playing-netease#128]
![image](https://user-images.githubusercontent.com/109365448/229350916-411288eb-aea9-4a5f-bed2-b08b5177593d.png)
如图，在1440X900分辨率时歌曲信息会和评论区错位，如果关闭评论区可以缓解问题，但是退出重进后歌曲信息也会消失
![image](https://user-images.githubusercontent.com/109365448/229350975-a157a796-fc02-4739-8900-f807197141b2.png)
（此时无法滚动，只能滚歌词）

**Comment by solstice23** [comment]
装了 elaina 主题？在主题设置里关掉播放页面的开关

**Comment by Colorfuldiamond** [comment]
感谢大佬，问题解决了
