### ISSUE TITLE
专辑封面不清晰

### ISSUE THREAD

**Issue by LJY7812** [solstice23/refined-now-playing-netease#13]
可以做一个左侧封面大小调节

**Comment by LJY7812** [comment]
如图：
![image](https://user-images.githubusercontent.com/103030400/211128068-15d106b5-b7ee-4ea6-8609-4121739bf2f0.png)

**Comment by solstice23** [comment]
![image](https://user-images.githubusercontent.com/23134847/211213276-daf04afe-0653-42bc-8b31-2728583d1dc9.png)
上一个版本就有了
