### ISSUE TITLE
歌词与歌曲不同步，歌词提前于歌曲

### ISSUE THREAD

**Issue by MNDT497996** [solstice23/refined-now-playing-netease#130]
作者您好，不知道是我的问题还是插件问题，我的插件出现了歌词与歌曲不同步问题吗，歌词要提前于歌曲，我试过重装better ncm以及网易云和重启电脑或是卸载其他插件只保留Re find [newplaying，但都不奏效，唯有卸载refindnewplaying后问题才得以解决，我也不知道是我的设备有问题还是插件存在bug，希望作者能看下原因，谢谢]
<img width="767" alt="屏幕截图 2023-04-03 154125" src="https://user-images.githubusercontent.com/129729118/229443562-d79984b5-8db5-4eb4-8cc8-b6f27270f45c.png">

**Comment by solstice23** [comment]
@MNDT497996 检查下设置中的全局偏移
