### ISSUE TITLE
[功能建议]恢复局部背景功能

### ISSUE THREAD

**Issue by PseudoFanta** [solstice23/refined-now-playing-netease#131]
在大约2.6.x版本时仍存在的局部背景功能可以为播放页面带来更清楚的功能划分。
然而在更新到2.16之后发现这一功能遭到移除。如果有可能的话烦请尊敬的开发者考虑恢复的可能性。
礼。

**Comment by solstice23** [comment]
下一个版本加到实验性设置好了
