### ISSUE TITLE
[BUG]多余的音量按钮

### ISSUE THREAD

**Issue by SteveXu9102** [solstice23/refined-now-playing-netease#134]
更新至2.17.0后底栏出现了多余的音量按钮，且点击后似乎没有实现任何功能

如何复现：打开软件就能看到

版本信息如下图
![屏幕截图 2023-04-10 124028](https://user-images.githubusercontent.com/68725147/230827807-bd600cd3-98ad-46f9-a118-00a870e229ad.png)

问题如下图（注：当窗口未最大化时或开启Material You悬浮底栏时该按钮可能遮挡其他功能按钮，影响使用）
![屏幕截图 2023-04-10 124115](https://user-images.githubusercontent.com/68725147/230827865-aa05f515-a677-407a-9826-93105225acf8.png)
![屏幕截图 2023-04-10 124143](https://user-images.githubusercontent.com/68725147/230827868-246b62ae-b542-4a66-8347-a94d59b353ed.png)

**Comment by solstice23** [comment]
@SteveXu9102 是否安装了倍速插件

**Comment by SteveXu9102** [comment]
安装了插件PlaybackRate

**Comment by SteveXu9102** [comment]
刚翻了PlaybackRate那边的Issues看到了同样的问题，是我疏忽了，不好意思。
目前出现新情况：倍速调整按钮直接消失了。
