### ISSUE TITLE
部分播放条件下，进度条悬浮歌词没有刷新

### ISSUE THREAD

**Issue by 975914892** [solstice23/refined-now-playing-netease#135]
BetterNCM：1.2.0
插件版本：2.17.0
网易云版本：2.10.8

问题一：私人FM播放时没有进度条悬浮歌词功能

问题二：当先播放自己歌单歌曲后，再选播客的音乐时，悬浮歌词没有更新，还是之前的歌词，（另一款插件Rulyrics有更新）
![image](https://user-images.githubusercontent.com/40827387/230940529-08b4a23a-c0a0-4d1e-ab23-e81eee548316.png)

![image](https://user-images.githubusercontent.com/40827387/230940569-3e69eb72-5046-4c7c-bfc7-920b4343b639.png)

问题三：不知是不是我的问题，插件的配置无法保存，每次重启网易云就重置了

**Comment by solstice23** [comment]
3 是不是在设置里点重启了

那个重启会影响插件配置的保存，正常重载或者退出就可以了

**Comment by solstice23** [comment]
问题1 2 待修复

**Comment by 975914892** [comment]
> 

是点右上角X退出的，等完全关闭后，再打开网易云，发现没保存配置，比如歌词模糊，字体等，您那边能正常保存是吗

**Comment by 975914892** [comment]
> 3 是不是在设置里点重启了
> 
> 那个重启会影响插件配置的保存，正常重载或者退出就可以了

是点右上角X退出的，等完全关闭后，再打开网易云，发现没保存配置，比如歌词模糊，字体等，您那边能正常保存是吗

**Comment by solstice23** [comment]
我这边测试是可以的
保存使用了 localStorage，某些情况下关闭的时候不会写入进去，其他使用了该保存方式（几乎所有）的插件都会有这个问题
我接下来看看要不要改成 fs 读写解决这个问题

**Comment by 975914892** [comment]
> 我这边测试是可以的 保存使用了 localStorage，某些情况下关闭的时候不会写入进去，其他使用了该保存方式（几乎所有）的插件都会有这个问题 我接下来看看要不要改成 fs 读写解决这个问题

好的，辛苦，静候佳音
