### ISSUE TITLE
[功能建议]给逐字添加发光效果

### ISSUE THREAD

**Issue by horace111** [solstice23/refined-now-playing-netease#137]
![屏幕截图 2023-04-15 212121](https://user-images.githubusercontent.com/130844293/232226766-87f2c24c-1a5d-42eb-8aa3-555f415e33ce.png)
就像这样

**Comment by solstice23** [comment]
已添加

**Comment by rainyorange** [comment]
![image](https://user-images.githubusercontent.com/36807368/232515554-dab6dff9-6dbf-41ea-b967-7d84459ffb43.png)
少许发光效果被歌词框挡住了

**Comment by solstice23** [comment]
已经修复，等会发版
