### ISSUE TITLE
[bug反馈]分享按钮点击后分享界面显示不完整

### ISSUE THREAD

**Issue by rainyorange** [solstice23/refined-now-playing-netease#139]
![QQ图片20230416171603](https://user-images.githubusercontent.com/36807368/232289747-c431a04f-d7ce-4986-a32f-aac4f197ad34.png)

**Comment by rainyorange** [comment]
这是我用了啥 插件冲突了吗

**Comment by solstice23** [comment]
无法复现，请发一下插件列表

**Comment by rainyorange** [comment]
![image](https://user-images.githubusercontent.com/36807368/232528050-e39ee1b4-7c20-48cc-b4a7-b561123e27e2.png)

**Comment by rainyorange** [comment]
其实有办法复现（）个性fm把分享框打开后 拖到屏幕外边就那啥了（）

**Comment by solstice23** [comment]
https://user-images.githubusercontent.com/23134847/232544035-46fb0926-355c-44d3-9d7b-805fc604412c.mp4

**Comment by rainyorange** [comment]
纯白是因为与light-dark-theme-switcher冲突

**Comment by solstice23** [comment]
纯白的修复了，一会发版
但是拖出去的复现不了

**Comment by rainyorange** [comment]
这个light-dark-theme-switcher已经不在插件库了（）

**Comment by solstice23** [comment]
在的，打开下面开发者模式依赖项，在里面

**Comment by rainyorange** [comment]
Uploading 2023-04-18 00-29-52_Trim.mp4…

**Comment by rainyorange** [comment]
https://user-images.githubusercontent.com/36807368/232552410-7ac7675b-8900-4c9f-a958-53b3638fae64.mp4

**Comment by rainyorange** [comment]
更新了之后fm底栏透明的问题解决了，但是这框还是能拖下去

**Comment by solstice23** [comment]
草了 我这是拖不下去的 删除其他插件排查看看

**Comment by rainyorange** [comment]
![CE_6{RQP 3{T@BAJGTH{IW4](https://user-images.githubusercontent.com/36807368/232553578-3c8d63e7-e1cc-4406-a715-b39d11325c80.png)
是BGEnhanced

**Comment by solstice23** [comment]
只装 BGE 也会出现能拖到外面的情况吗

**Comment by rainyorange** [comment]
是的，只装BGE下方的阻挡就消失了

**Comment by solstice23** [comment]
那这个是 BGE 的问题了，去它的 repo 发 issue 吧（
