### ISSUE TITLE
2.10.6 评论区样式问题

### ISSUE THREAD

**Issue by Skimige** [solstice23/refined-now-playing-netease#141]
猜了一下是不是网易云版本稍微旧了点，更到 2.10.8 果不其然自己好了

2.10.6 截图（区别在于鼠标 hover）

![Snipaste_2023-04-17_16-29-59](https://user-images.githubusercontent.com/9017470/232433603-f072d20c-9817-487b-8ac1-1a7d1dbed275.png)
![Snipaste_2023-04-17_16-30-06](https://user-images.githubusercontent.com/9017470/232433611-bda948a1-0546-4126-a4cd-b76f697f4133.png)

2.10.8 截图

![Snipaste_2023-04-17_16-47-58](https://user-images.githubusercontent.com/9017470/232433674-ae5a381c-a9cc-4a5e-88ee-e8dd55d405f5.png)

**Comment by solstice23** [comment]
草 没想到是版本问题
这个评论区样式是 MDYou 中的，待修复

**Comment by solstice23** [comment]
请更新到最新网易云
或者开启此开关
![image](https://user-images.githubusercontent.com/23134847/232550094-b6894612-e3f4-43ff-a3e1-3a421291193e.png)
