### ISSUE TITLE
[BUG] 与 BGEnhanced 一起使用，评论区翻页后网易云页面错位

### ISSUE THREAD

**Issue by lgc2333** [solstice23/refined-now-playing-netease#142]
https://user-images.githubusercontent.com/59048777/233173802-395b428a-eead-47f3-8479-fb2b6d4800f4.mp4

**Comment by solstice23** [comment]
可能是 Motheme 的问题，我这边无法复现

**Comment by KeeLee2005** [comment]
单独装BGEnhanced也会这样。。。无论有没有装主题或其他插件，只要有BGEnhanced，评论区翻页就会出现界面错位问题。

https://user-images.githubusercontent.com/92454987/235455386-b505c9b8-6448-46ed-8f5c-037ef300ea41.mp4
