### ISSUE TITLE
辉光效果无法关闭

### ISSUE THREAD

**Issue by sy999999ys** [solstice23/refined-now-playing-netease#143]
关闭辉光效果后，前面的辉光效果没了，但每句的最后一个字的辉光依然有。
![cloudmusic_QYfp7EI7rc](https://user-images.githubusercontent.com/51683562/233647217-dcffb4cd-a440-4147-8efb-8227c5f403e9.png)

**Comment by solstice23** [comment]
已添加开关
![image](https://user-images.githubusercontent.com/23134847/233709571-aa906517-d3aa-465e-8d21-d1b97708121e.png)
