### ISSUE TITLE
遇到的所有问题反馈汇总

### ISSUE THREAD

**Issue by 286460410** [solstice23/refined-now-playing-netease#144]
1.颜色模式无法跟随win10的夜间模式系统自动更换
2.文字阴影和文字辉光效果似乎一样（除了在暗色模式下）
3.优化底栏项点击不了
4.逐字动画上浮和滑动好像没区别（可能是我眼拙）
5.底栏左边四个功能点不了

**Comment by 286460410** [comment]
还有希望可以有关闭长音词语发光的选项
望聆听，感谢

**Comment by solstice23** [comment]
1. 跟随的是这个 
![image](https://user-images.githubusercontent.com/23134847/233674043-03d313a7-b6fc-434e-a63d-123c324bb3a8.png)

2. 不一样，一个是黑色，一个是文字本身的颜色
3. 如果用了 Ark / Relive 主题，主题会自动关闭该选项
4. 有区别，仔细观察
5. 重启看看，插件没对这部分改动，网易云自身有时会出现这样的问题
6. 关闭长音词语发光的选项 准备做了

**Comment by solstice23** [comment]
![image](https://user-images.githubusercontent.com/23134847/233709602-bf4a82ab-2e9e-4cf3-a0d4-c6a72950e2db.png)

**Comment by 286460410** [comment]
> 1. 跟随的是这个
>    ![image](https://user-images.githubusercontent.com/23134847/233674043-03d313a7-b6fc-434e-a63d-123c324bb3a8.png)
> 2. 不一样，一个是黑色，一个是文字本身的颜色
> 3. 如果用了 Ark / Relive 主题，主题会自动关闭该选项
> 4. 有区别，仔细观察
> 5. 重启看看，插件没对这部分改动，网易云自身有时会出现这样的问题
> 6. 关闭长音词语发光的选项 准备做了

跟随系统还是没有找到 可以细说一下吗 thanks

**Comment by solstice23** [comment]
Windows 设置 - 个性化 - 颜色
