### ISSUE TITLE
c盘缓存过大

### ISSUE THREAD

**Issue by MF66666** [solstice23/refined-now-playing-netease#166]
每次更换歌曲都会重复本地缓存几遍封面 并且重新听也会 对于我这类听歌多的人来说 一个星期都有三四个g了 喜欢添加歌曲标识不必重复浪费资源

**Comment by TatleCat** [comment]
记得先改缓存位置

**Comment by TatleCat** [comment]
定期清理就好了,记得先改缓存位置
如果你是喜欢听无损的用户
即使是一天内所使用的容量也是合理的
[这里是非作者回复,别看错了]

**Comment by solstice23** [comment]
缓存并非 RNP 的机制。是 FluentCover 的
