### ISSUE TITLE
【建议】添加自定义功能

### ISSUE THREAD

**Issue by LimeBow-Studios** [solstice23/refined-now-playing-netease#172]
# 建议
添加用户上传**cover（额，应该是叫这个吧），歌曲和歌词（中日英罗马字分别上传）**并显示的功能
**_网易云好多歌词和翻译都有误qAq_**
这样可以more beautiful and handsome<del>（不是放洋屁）</del>

话说我们可以直接录制本插件界面的视频发到网站上而不做注释吗？
# Thanks for the development~
<del>（这个是了[doge]）</del>

**Comment by solstice23** [comment]
> 添加用户上传**cover（额，应该是叫这个吧），歌曲和歌词（中日英罗马字分别上传）**并显示的功能

这个需要服务端，超出了本插件的范围

> 说我们可以直接录制本插件界面的视频发到网站上而不做注释吗？

完全没问题

**Comment by yangnuozhen** [comment]
> 话说我们可以直接录制本插件界面的视频发到网站上而不做注释吗？

https://github.com/MicroCBer/BetterNCM#%E6%B3%A8%E6%84%8F

也许不要透露BetterNCM会是更好的选择（

**Comment by FinaFina233** [comment]
如果我没理解错的话，隔壁插件有这功能
![image](https://github.com/solstice23/refined-now-playing-netease/assets/52440333/e54fd97a-0859-4ed8-a2f5-55914dc44c7d)
![image](https://github.com/solstice23/refined-now-playing-netease/assets/52440333/01df17ad-feee-4d23-b071-2d0f0eba4c50)

**Comment by LimeBow-Studios** [comment]
感谢回答
