### ISSUE TITLE
【建议】日语歌词使用平假名标注

### ISSUE THREAD

**Issue by dogliu666** [solstice23/refined-now-playing-netease#199]
在原有**日语歌词上方增加平假名标注**，单独使用一行罗马音标注不便于观看
可参考QQ音乐样式
![屏幕截图 2024-01-28 224743](https://github.com/solstice23/refined-now-playing-netease/assets/106862353/9706f35e-bcf9-4749-9715-10d9c5ea91ef)
![屏幕截图 2024-01-28 224202](https://github.com/solstice23/refined-now-playing-netease/assets/106862353/69e87531-0ed0-4d51-9f06-b78ead801419)

**Comment by FinaFina233** [comment]
不是已经有插件了吗
