### ISSUE TITLE
feat: allow background transparency

### ISSUE THREAD

**Issue by MicroCBer** [solstice23/refined-now-playing-netease#2]
![image](https://user-images.githubusercontent.com/66859419/204072136-0ed18aac-1b00-4df9-9c1b-523ace6e28c5.png)

kinda strange, I suggest adding an option to allow making the background transparent

**Comment by solstice23** [comment]
Do you mean it conflicts with the background-enhancing plugin? I will add an option to fix this, only when coexisting with the background plugin.

**Comment by MicroCBer** [comment]
> Do you mean it conflicts with the background-enhancing plugin? I will add an option to fix this, only when coexisting with the background plugin.

It actually will appear with any themes with a background, not only bg enhanced

**Comment by solstice23** [comment]
So showing the option all time is better. And is this option a slider to adjust the transparency of the blur layer, a switch to confine the blur layer in a smaller area, or both?

**Comment by MicroCBer** [comment]
probably both, then people can choose by their preference

**Comment by solstice23** [comment]
![screenshot3](https://user-images.githubusercontent.com/23134847/204108254-1ee42ba2-7e4f-40ec-b55a-151492f97b88.png)

**Comment by solstice23** [comment]
I want to open a PR to add a window radius API. But I found it had been done a few hours ago when I forked the repo, lol
Once the new version is out, I will add an option to control that.

**Comment by MicroCBer** [comment]
> I want to open a PR to add a window radius API. But I found it had been done a few hours ago when I forked the repo, lol
Once the new version is out, I will add an option to control that.

The function is planned to be built-in as it's actually a function of betterncm itself so it's not reasonable to install any other plugins to use it. I'd like to add a switch in the plugin manager menu to control it.
