### ISSUE TITLE
私人FM播放时无法显示“正在播放”页

### ISSUE THREAD

**Issue by pchpub** [solstice23/refined-now-playing-netease#20]
<img width="229" alt="image" src="https://user-images.githubusercontent.com/73123406/213461800-fef142aa-812d-4142-aa45-21b698ba0a6d.png">
点击如图所示图标无反应

网易云版本： 2.10.6

betterncm版本： 1.0.0

**Comment by solstice23** [comment]
私人 FM 本来就是这个界面显示详情
之后应该会重写，然后适配这个页面
