### ISSUE TITLE
Feature:支持自定义模糊歌词的行数

### ISSUE THREAD

**Issue by liaosunny123** [solstice23/refined-now-playing-netease#23]
支持自定义模糊歌词的行数，如模糊歌词开启下，清晰的行数为3或者5

**Comment by solstice23** [comment]
正在重写全新的歌词组件
https://user-images.githubusercontent.com/23134847/215256660-79e6bfe5-9dd0-4fd8-b72c-9ccce61e2dbf.mp4

![image](https://user-images.githubusercontent.com/23134847/215256632-ac71a8a6-66ef-4d86-b98a-6b8b3d9e534d.png)

**Comment by liaosunny123** [comment]
加油！感谢作者了。我刚刚clone了一下，准备pr过去的，结果一直没找到lyric-blur的具体功能在哪。。。

**Comment by solstice23** [comment]
之前的是 CSS :not() 选择器，网易云的 CEF 版本太老没有 :has 选择器，所以没法用纯 CSS 做到前后具体模糊几句
重写以后会提供更多选项
