### ISSUE TITLE
Feature: 可以调整歌词跳转指示器颜色

### ISSUE THREAD

**Issue by ky678** [solstice23/refined-now-playing-netease#28]
如图，感觉歌词是浅色的看着有点怪，如果背景也是浅色就更难看了
希望能改成歌词一样的那种颜色，或者出一个在白色和黑色之间调整的设置
![image](https://user-images.githubusercontent.com/75194598/215311757-75483bdc-4bd9-426a-b52f-fcd30d5f2718.png)

**Comment by solstice23** [comment]
正在重写新版歌词
