### ISSUE TITLE
Bug:当同时使用此插件和material you主题，音质选择窗口字体显示异常

### ISSUE THREAD

**Issue by ky678** [solstice23/refined-now-playing-netease#29]
如图，只要鼠标在“无损”或者选择窗口上就会触发bug
![image](https://user-images.githubusercontent.com/75194598/215313528-b2fda768-88b0-412d-9a73-71a65ec77afc.png)

**Comment by cow-your-sister** [comment]
![image](https://user-images.githubusercontent.com/88882901/215696902-265e4847-cdfd-48f3-adc3-91a0d9d32cd7.png)
t同样的问题
