### ISSUE TITLE
无法正确安装此插件

### ISSUE THREAD

**Issue by allut123** [solstice23/refined-now-playing-netease#30]
当更新版本2.0.1（release2023/1/30）时，无法正确更新和安装，不使用market安装同样有此问题

**Comment by Helpless-Mao** [comment]
问题同上

**Comment by MKingss** [comment]
问题同上

**Comment by solstice23** [comment]
更新 betterncm 到 nightly 最新版

**Comment by allut123** [comment]
> 更新 betterncm 到 nightly 最新版

谢谢，问题已经解决

**Comment by Estar-dev-star** [comment]
> 

能麻烦您为我详细解答一下解决方法吗

**Comment by PigeonP** [comment]
> 更新 betterncm 到 nightly 最新版

你好，我已经用BetterNCM Installer更新到1.0.0-nightly，还是无法安装；且用release下的包手动安装也无果（好像没有.plugin文件不识别，压缩包里我也没找到）【market内版本2.1.0（release1/31）】

**Comment by PigeonP** [comment]
> > 更新 betterncm 到 nightly 最新版
> 
> 你好，我已经用BetterNCM Installer更新到1.0.0-nightly，还是无法安装；且用release下的包手动安装也无果（好像没有.plugin文件不识别，压缩包里我也没找到）【market内版本2.1.0（release1/31）】

不对，好象是我的问题，更新完全装不上了🤔

**Comment by getupwhy** [comment]
同问

**Comment by getupwhy** [comment]
测试通道可以安装
