### ISSUE TITLE
正在播放页面歌词上移问题

### ISSUE THREAD

**Issue by Siuroe** [solstice23/refined-now-playing-netease#33]
1.点击全屏纯享后退出，歌词出现上移且重新打开正在播放页面依旧
![image](https://user-images.githubusercontent.com/106878922/215496620-33fa44aa-f229-4ba0-86fa-40de6add513d.png)
2、正在播放页面打开主题，出现如下状况
![image](https://user-images.githubusercontent.com/106878922/215496793-039531d0-fdcc-4ee6-800a-aa6412123e06.png)

**Comment by solstice23** [comment]
已修复，还没发布

**Comment by Siuroe** [comment]
> 已修复，还没发布

问题2依然存在
![image](https://user-images.githubusercontent.com/106878922/215829711-a72f48a0-9dcb-4c88-bb97-f5b312aaa282.png)
版本2.2.0，兼容性检查完成
![image](https://user-images.githubusercontent.com/106878922/215829939-3079d719-10a3-47cf-8cde-966faa7e176b.png)

**Comment by solstice23** [comment]
2 要 MDYou 这边更新，现在在忙别的，这两天会修
