### ISSUE TITLE
与Meterial You配合使用时，歌名专辑歌手的字的颜色与背景不匹配

### ISSUE THREAD

**Issue by zqs74** [solstice23/refined-now-playing-netease#34]
如图，在Meterial You也发issue了
<img width="792" alt="Snipaste_2023-01-31_11-32-55-621 裂缝中的阳光 - 林俊杰" src="https://user-images.githubusercontent.com/74396962/215656829-5ffdc3a5-d92f-4f8c-a7fb-359dfe2d1712.png">

**Comment by zqs74** [comment]
私人FM里的

**Comment by solstice23** [comment]
新版已修复
