### ISSUE TITLE
【Bug】歌词无法显示

### ISSUE THREAD

**Issue by cow-your-sister** [solstice23/refined-now-playing-netease#37]
![屏幕截图 2023-01-31 153754](https://user-images.githubusercontent.com/88882901/215697319-f6c0b999-d6c3-490c-9dc9-776ea3611929.png)
设置如图，歌词无法显示，对于所有歌曲
与MaterialYou搭配使用

**Comment by solstice23** [comment]
看兼容性检查了吗

**Comment by cow-your-sister** [comment]
> 看兼容性检查了吗
看了，缓存清理过，开启GPU加速。
重载BetterNCM后会恢复，放几首歌又会出现bug
还有个问题，新的[issue](https://github.com/solstice23/refined-now-playing-netease/issues/38)
