### ISSUE TITLE
【Suggestion】希望把歌词超长的断行和上下句歌词之间的断行区别一下

### ISSUE THREAD

**Issue by cow-your-sister** [solstice23/refined-now-playing-netease#38]
![image](https://user-images.githubusercontent.com/88882901/215702867-90469cee-7ab3-4c39-9531-1ff12c4ce5f2.png)
如图，正在播放的这句歌词翻译被合并到了下一行歌词，但这行歌词和下一行歌词之间的间隔与上下句歌词之间的间隔一样

**Comment by solstice23** [comment]
parser的问题，我看看
