### ISSUE TITLE
歌词滚动显示问题

### ISSUE THREAD

**Issue by DancingSnow0517** [solstice23/refined-now-playing-netease#4]
在歌词滚动时，当前的歌词会有个加粗一样的效果，会导致有突然变大的感觉，但是中间本身已经放大了，建议取消加粗的效果

**Comment by Junsang2000** [comment]
不过我喜欢这个加粗的效果，只是太突兀了，而且字体不统一，希望增加更多自定义的功能，比如改变字体，字体大小，歌词整体占比，封面大小。还有就是封面太模糊了，不知道能不能调用更清楚的歌曲封面

**Comment by solstice23** [comment]
可以考虑引用可变思源黑体，但是大小 30 多 m

**Comment by KJH-x** [comment]
似乎是字体放大之后发生了文字重新排版，也许可以在放大之前就重排好，避免歌词闪烁

**Comment by imusic-487** [comment]
好像是因为放大导致了重新排版，甚至还有先放大后加粗的情况，感觉不太协调。要不就是只放大

**Comment by solstice23** [comment]
在做可视化背景，做完准备重写歌词了

**Comment by imusic-487** [comment]
好的 辛苦了。我发现就是英文下的歌词会有一个先放大后加粗然后重新排版的问题 中文看起来是妹什么大问题 应该是渲染的问题？我也不懂哈哈哈

**Comment by solstice23** [comment]
已重写歌词
