### ISSUE TITLE
无法打开播放页面

### ISSUE THREAD

**Issue by PJnoeru** [solstice23/refined-now-playing-netease#41]
![image](https://user-images.githubusercontent.com/41642563/215929827-e84a36c7-0d0f-4fc6-8178-6438dec60032.png)
如图无法正常显示播放页面
![image](https://user-images.githubusercontent.com/41642563/215929921-56a41da8-4c8e-42a2-aa03-a52aee69d636.png)
兼容性测试如图

**Comment by PJnoeru** [comment]
![image](https://user-images.githubusercontent.com/41642563/215930362-6c1f6ae3-c871-4d75-8055-048af575cd4a.png)

**Comment by MKingss** [comment]
加1
