### ISSUE TITLE
全屏模式/专辑封面居中

### ISSUE THREAD

**Issue by 2822122014** [solstice23/refined-now-playing-netease#42]
1.希望添加全屏模式，直接覆盖任务栏
2.专辑封面太靠左了，希望能往右边来一点，居中显示（在歌词左边那部分居中）

**Comment by Helpless-Mao** [comment]
借个楼 希望开放专辑封面位置权限，自己调位置

**Comment by solstice23** [comment]
居中的现在垂直和水平都做了，下一个版本加全屏

**Comment by Helpless-Mao** [comment]
给大佬跪了 磕一个

**Comment by 2822122014** [comment]
> 居中的现在垂直和水平都做了，下一个版本加全屏

大佬666，真nice！！！
