### ISSUE TITLE
【suggestion】希望把“模糊”选项的加载逻辑优化一下

### ISSUE THREAD

**Issue by cow-your-sister** [solstice23/refined-now-playing-netease#43]
当前版本适用“模糊”选项的GPU占用异常高，推测是每加载一遍歌词就把背景重新渲染（跟流体效果的逻辑相同）。

https://user-images.githubusercontent.com/88882901/215938615-852c9c31-f42a-40fc-8a34-2fc8a3d45151.mp4

希望改成每首歌只渲染一次，作为背景，然后在它上面渲染歌词效果，也就是多建几个图层

**Comment by solstice23** [comment]
![image](https://user-images.githubusercontent.com/23134847/215960965-a957c0a2-3dbf-4083-9bd1-53756d585944.png)

**Comment by solstice23** [comment]
现在的模糊和最开始的版本的一样的，加载一次就不重绘的，可能是别的因素造成 GPU 占用高
