### ISSUE TITLE
关于一直存在的一个显示BUG，在局部背景功能时就出现的

### ISSUE THREAD

**Issue by QingmingHaruaki** [solstice23/refined-now-playing-netease#44]
![@Z34HMCB_M1FR6ES7 R7CY2](https://user-images.githubusercontent.com/122613083/215951483-de965bca-092b-4143-ae17-31cc8252a21c.png)
如上图，这个BUG在局部背景时就出现了，具体为：初次打开网易云，然后打开歌词页，歌词页和主页会重叠显示，并且歌词页和主页的按钮都能点（关闭后再次打开就不会出现了
![image](https://user-images.githubusercontent.com/122613083/215952302-cf38e547-dbb3-43ce-88e5-9597f688a0aa.png)
上图为插件列表，网易云版本为2.10.6，betterncm版本为1.0.0-nightly

**Comment by solstice23** [comment]
![image](https://user-images.githubusercontent.com/23134847/215955515-2d4610b0-4ca7-410f-8799-9da2736a5855.png)

这是测试环境的插件列表，复现不了此问题

尝试二分移除一下插件，看看是和哪个插件起了冲突，然后我复现并修复

**Comment by QingmingHaruaki** [comment]
应该是Motheme插件，移除后就没有出现这个情况了

**Comment by solstice23** [comment]
确认了是 MoTheme 的问题，帮你 @mo-jinran
