### ISSUE TITLE
请指明思源黑体需要的字体

### ISSUE THREAD

**Issue by YSYD0315** [solstice23/refined-now-playing-netease#46]
如题, 想尝试使用思源黑体功能, 并且从[思源黑体项目](https://github.com/adobe-fonts/source-han-sans)下载并安装了许多字体. 更改后仍然无法正常使用, 想询问到底需要什么字体(简繁日韩)

**Comment by solstice23** [comment]
重启网易云

**Comment by YSYD0315** [comment]
尬了 没想到这么简单...... 打扰
