### ISSUE TITLE
Font color does not suit well when the cover is mostly black

### ISSUE THREAD

**Issue by MicroCBer** [solstice23/refined-now-playing-netease#5]
![image](https://user-images.githubusercontent.com/66859419/205257863-4eb6d304-6dd6-4a11-9bb3-2d2b151dd413.png)

![7M09C0 @Q}%)_IK7@BOO}AX](https://user-images.githubusercontent.com/66859419/205257808-b8513a6f-4e03-4990-bcf0-0f554f8cf803.png)

refinednowplaying遇到黑底专辑图片就麻了
(帮人发的)

**Comment by solstice23** [comment]
无法复现（）
![image](https://user-images.githubusercontent.com/23134847/205278677-49222e11-9dac-40b4-9f51-531b0d960908.png)
![image](https://user-images.githubusercontent.com/23134847/205278695-4d165994-338c-4d69-a2d4-4582cf80eaba.png)
