### ISSUE TITLE
feat:部分场景字体颜色加强

### ISSUE THREAD

**Issue by liaosunny123** [solstice23/refined-now-playing-netease#56]
建议在暗色环境下加强”译“，"音"，"逐字"的亮度：
![image](https://user-images.githubusercontent.com/30096937/216629812-a2aa5e7d-885d-43a0-985f-d0ae5daa9552.png)
建议在高亮度下减弱评论的亮度：
![image](https://user-images.githubusercontent.com/30096937/216630000-7a486f79-1425-4053-b814-3c0c5798fe63.png)
或者直接修改这些地方字体的颜色，以适应对应的环境

**Comment by solstice23** [comment]
第一个对应开关不能用的时候（比如没有翻译的时候）就会变得很透明
第二个 字体应该是黑色的 请提供已安装的插件列表

**Comment by liaosunny123** [comment]
LibFrontendPlay-0.1.0.plugin

**Comment by liaosunny123** [comment]
> 第一个对应开关不能用的时候（比如没有翻译的时候）就会变得很透明 第二个 字体应该是黑色的 请提供已安装的插件列表

感觉设置成不可见也许会更好？
