### ISSUE TITLE
浅色背景难以看清顶部 UI

### ISSUE THREAD

**Issue by Skimige** [solstice23/refined-now-playing-netease#57]
![image](https://user-images.githubusercontent.com/9017470/216765341-fe4ef07c-d3b7-45ae-b240-989f27c0261a.png)

尝试了多种模式和暗化值，均没有特别满意的结果。

## 系统信息

Windows 10 22H2
网易云音乐 2.10.6.200601
BetterNCM 1.0.1

## 插件列表

- RefinedNowPlaying 2.3.3
- MoTheme 1.2.0
- BGEnhanced 0.2.7
- TinyNCM 0.2.3
- InfLink 0.1.6
- VisualRecord 1.0.1
- StylesheetLoader 0.1.2 (required by MoTheme)

**Comment by solstice23** [comment]
草 这个当时只在 MD You 主题的联动中解决了下，没考虑到没装主题的情况（
我看看，能不能反个色

**Comment by Skimige** [comment]
右上角的 UI 呢（左上角的前进后退听歌识曲我个人觉得丢了都行x

![image](https://user-images.githubusercontent.com/9017470/216981796-88ce3d53-64b6-4712-b836-a591f7f692ba.png)

（故意改颜色模式成暗色方便看清）

**Comment by solstice23** [comment]
其实适配了 MD You，所以我调试的时候没有发现
原生的图标应该就只能 invert
