### ISSUE TITLE
背景显示异常

### ISSUE THREAD

**Issue by nexmoe** [solstice23/refined-now-playing-netease#59]
![image](https://user-images.githubusercontent.com/16796652/216798847-31683bbd-ae5b-4e3b-bf6a-aa6856e10ed4.png)

大概是由 https://github.com/solstice23/refined-now-playing-netease/commit/d83deb3b3ead86859b880ee42e09abccc83ee848 导致的

**Comment by solstice23** [comment]
装了什么插件

**Comment by nexmoe** [comment]
> 装了什么插件

默认皮肤，把 z-index: -2; 去掉就正常了

**Comment by nexmoe** [comment]
> 装了什么插件

默认皮肤，把 z-index: -2; 去掉就正常了

**Comment by solstice23** [comment]
z-index 改成 -1 或者 0 可以吗

**Comment by nexmoe** [comment]
> z-index 改成 -1 或者 0 可以吗

-1 不行，0 可以

**Comment by solstice23** [comment]
那我改成 0 好了

**Comment by PrePan01** [comment]
同样问题！除了黑色皮肤播放页都会出现这个问题，求更新
