### ISSUE TITLE
首次安装后“完成并不再提示（重启）”点击后还会提示

### ISSUE THREAD

**Issue by CHN-WSchumacher** [solstice23/refined-now-playing-netease#61]
首次安装后“完成并不再提示（重启）”点击后还会提示，然后除了再点重启以外不能进行任何操作，如此循环
即使是只安装这一个插件也是如此
betterNCM版本1.0.1
网易云音乐版本2.10.6

**Comment by solstice23** [comment]
请更新 2.4.1，已经修复

临时解决方案是：
在网易云窗口按下 F12，点击顶上 Console，输入 `localStorage.setItem("refined-now-playing-wizard-done", "true");` ，回车，并重启网易云

**Comment by CHN-WSchumacher** [comment]
临时解决方案有效了，但是我安装的就是2.4.1版本出现的这个问题。
系统和软件都是刚新装的，在另一台旧电脑上反而没有这个问题。
Win10LTSC2021

**Comment by CHN-WSchumacher** [comment]
> 请更新 2.4.1，已经修复
> 
> 临时解决方案是： 在网易云窗口按下 F12，点击顶上 Console，输入 `localStorage.setItem("refined-now-playing-wizard-done", "true");` ，回车，并重启网易云
临时解决方案有效了，但是我安装的就是2.4.1版本出现的这个问题。
系统和软件都是刚新装的，在另一台旧电脑上反而没有这个问题。
Win10LTSC2021

**Comment by CHN-WSchumacher** [comment]
> 请更新 2.4.1，已经修复
> 
> 临时解决方案是： 在网易云窗口按下 F12，点击顶上 Console，输入 `localStorage.setItem("refined-now-playing-wizard-done", "true");` ，回车，并重启网易云

临时解决方案有效了，但是我安装的就是2.4.1版本出现的这个问题。
系统和软件都是刚新装的，在另一台旧电脑上反而没有这个问题。
Win10LTSC2021

**Comment by solstice23** [comment]
我等会再推一个新版

**Comment by CHN-WSchumacher** [comment]
> 我等会再推一个新版

感谢
