### ISSUE TITLE
更新至2.3.3后的版本后，播放页面的设置按钮消失

### ISSUE THREAD

**Issue by Suxmx** [solstice23/refined-now-playing-netease#62]
更新完设置的按钮消失，以及“封面水平对齐”与“封面垂直对齐”的设置一直不起作用，不清楚是bug还是与其他插件的不兼容

**Comment by solstice23** [comment]
现在 2.4.2 了（

**Comment by Suxmx** [comment]
更新之后发现按钮没了，回退到2.3.3了orz

**Comment by solstice23** [comment]
按钮变成设置了
![image](https://user-images.githubusercontent.com/23134847/217037613-cde4babf-5266-436b-9352-b78126043eb2.png)

**Comment by Suxmx** [comment]
![image](https://user-images.githubusercontent.com/33772816/217037837-2cba269e-7ef1-41e2-8616-072da94dc5d6.png)
我这里好像还是找不到

**Comment by Suxmx** [comment]
![image](https://user-images.githubusercontent.com/33772816/217038015-79128f7b-43b3-49da-a8d2-3f7e4b69a96c.png)

**Comment by solstice23** [comment]
F12 看下有没有错误，这连歌词控件都没注入

**Comment by Suxmx** [comment]
![image](https://user-images.githubusercontent.com/33772816/217038494-eb913b67-51bd-45b5-ae1b-fbe512ca75f3.png)
好像是有很多报错

**Comment by solstice23** [comment]
更新一下试试（刚推，如果没有检测到就等一分钟）

**Comment by solstice23** [comment]
![image](https://user-images.githubusercontent.com/23134847/217041887-32603ca5-b5bf-4a97-a05e-601fd4fb621b.png)
点一下这里看看

**Comment by Suxmx** [comment]
可以的

**Comment by solstice23** [comment]
tg / qq?

**Comment by Suxmx** [comment]
加我qq可以吗？424504326

**Comment by ylingu** [comment]
> tg / qq?
有同样的问题，已经更新到2.5.1版本了，尝试过重装还是不行，希望大佬帮忙，tg：t.me/absxfls

**Comment by solstice23** [comment]
更新网易云版本就可以了

> > tg / qq?
> > 有同样的问题，已经更新到2.5.1版本了，尝试过重装还是不行，希望大佬帮忙，tg：t.me/absxfls
