### ISSUE TITLE
播放界面底部问题

### ISSUE THREAD

**Issue by akikiri** [solstice23/refined-now-playing-netease#63]
鼠标进入播放界面时，底部升起动画如果未播放完就将鼠标移出窗口外，会闪现回隐藏底部状态，用鼠标一直在边界晃会一直闪现

**Comment by solstice23** [comment]
这个很难修，我准备改掉，改成鼠标在窗口外是环形进度条，在窗口内是普通进度条，如何

**Comment by solstice23** [comment]
应该是修复了，没有做进一步的防抖，但很少触发了

**Comment by akikiri** [comment]
> 这个很难修，我准备改掉，改成鼠标在窗口外是环形进度条，在窗口内是普通进度条，如何

我认为调整成在鼠标移出窗口外时不要立即缩回动画，而是过一段时间缩回，就和鼠标在窗口内不动一段时间缩回一样，这样至少不会触发鬼畜了，现在的调整还是时不时会触发
