### ISSUE TITLE
发现一个小Bug

### ISSUE THREAD

**Issue by zp9999** [solstice23/refined-now-playing-netease#67]
如果在评论区点击了下一页，下面的几个控制键就会整体向上挪动一下，同时左上角的“关闭歌词页面”的按钮就消失了（就剩一个全屏按钮了），不能直接退出歌词页了。

**Comment by solstice23** [comment]
@zp9999 检查别的插件，RefinedNowPlaying + MaterialYou 不能复现

**Comment by zp9999** [comment]
确实是我的问题，我把StyleSnippet插件的“Material You主题进度条位置修改”关闭就可以了，谢谢你。
