### ISSUE TITLE
[插件Bug] 安装RefinedNowPlaying后无法正常显示歌词

### ISSUE THREAD

**Issue by BillZhong2008** [solstice23/refined-now-playing-netease#69]
# 问题描述
Windows 网易云音乐在使用 BetterNCM 安装 RefinedNowPlaying(下文简称rnp) 后无法正常的在播放页显示歌词。

# 问题复现
1. 使用PluginMarket安装rnp;
2. 重载BetterNCM并重启网易云音乐;
3. 成功安装rmp后打开播放页;
4. 发现该问题.

# 软件版本
## 网易云音乐
版本 2.10.6
Patch版本 5ad43a6
## Windows版本
版本 Windows 11 专业版 Insider Preview 22H2
操作系统版本 25290.1000

# 屏幕截图
![()$A( 3GL471ZF237K1TESI](https://user-images.githubusercontent.com/89178012/218151459-906fcdce-ec3d-492f-a36a-7bce0f1d2c53.JPG)
![JAKO20807ZKM1KP 3%NVJ$H](https://user-images.githubusercontent.com/89178012/218151479-548503de-697d-438e-823d-e83370cb9ea1.JPG)
![NAX1N8Z8J MBEK%STTD_@HF](https://user-images.githubusercontent.com/89178012/218151488-e3e5a413-644d-4d4e-8473-fa87b966c7b7.JPG)
![5~`%0@~YKE%1SUAC1VVHJ 8](https://user-images.githubusercontent.com/89178012/218151493-b5a4cd20-323e-4869-b744-e151c2383a03.JPG)
_↑已清空hijack缓存_

**Comment by solstice23** [comment]
重启一下网易云
