### ISSUE TITLE
在其他页面点击进入歌词页面时，背景会卡一下再填满底栏，很不流畅

### ISSUE THREAD

**Issue by hzb666** [solstice23/refined-now-playing-netease#73]

**Comment by ky678** [comment]
一样，用动态流体很卡而且底下有渲染错误，电脑配置不低不是性能问题

**Comment by solstice23** [comment]
> 一样，用动态流体很卡而且底下有渲染错误，电脑配置不低不是性能问题

兼容性检查，开gpu渲染

**Comment by ky678** [comment]
> > 一样，用动态流体很卡而且底下有渲染错误，电脑配置不低不是性能问题
> 
> 兼容性检查，开gpu渲染

之前试过了
隐约记得是更新了betterncm才这样的，之前好像没有
版本是nightly最新

插件列表：
"C:\betterncm\plugins\InfLink-0.1.6.plugin"
"C:\betterncm\plugins\LibEAPIRequest-1.6.2.plugin"
"C:\betterncm\plugins\liblyric-1.0.0.plugin"
"C:\betterncm\plugins\MaterialYouTheme-2.0.8.plugin"
"C:\betterncm\plugins\MikuPlugin-0.1.2.plugin"
"C:\betterncm\plugins\PluginMarket.plugin"
"C:\betterncm\plugins\RefinedNowPlaying-2.6.0.plugin"
"C:\betterncm\plugins\RoundCornerNCM-0.1.2.plugin"
"C:\betterncm\plugins\StyleSnippet-0.2.0.plugin"
"C:\betterncm\plugins\What-is-the-cover-of-this-music-2.0.5.plugin"
"C:\betterncm\plugins\ActionEnhancement-0.1.6.plugin"
"C:\betterncm\plugins\FluentProgressBar-0.2.0.plugin"

**Comment by ky678** [comment]
补充一下，静态流体也有渲染错误，不过没有动态明显且没有卡顿

**Comment by ky678** [comment]
RIP BetterNCM
