### ISSUE TITLE
黑胶鲸鱼音效开启的图标有显示故障

### ISSUE THREAD

**Issue by Rothes** [solstice23/refined-now-playing-netease#76]
【正常】鲸鱼音效关闭时 或 开启非黑胶音效时（但两者之间显示的位置有些许偏差，可能因为开启时的ON图标）
![image](https://user-images.githubusercontent.com/47097395/218329584-8ae6ae5d-54c2-4267-a7c8-3bab6ec13bc5.png)

【BUG】鲸鱼音效开启黑胶音效时（有VIP图标）
![image](https://user-images.githubusercontent.com/47097395/218329612-e4115f67-69cd-41b4-907c-e53e8cfe5708.png)
官方图标为
![image](https://user-images.githubusercontent.com/47097395/218329635-5bd972c4-e5d4-46f0-a04f-af8c94cdc716.png)

**Comment by solstice23** [comment]
MD You 的问题

**Comment by Rothes** [comment]
已确认修复
