### ISSUE TITLE
【建议】获取高清的专辑封面

### ISSUE THREAD

**Issue by rainpenber** [solstice23/refined-now-playing-netease#8]
使用本插件以后，专辑封面的显示范围更大更舒适了，但是由于本身是低清图片，所以看起来比较糊
对比了一下原版的播放器，似乎播放界面默认就是获取的低清专辑封面
有没有办法获取和展示高清的专辑封面图片呢
![清晰度对比](https://user-images.githubusercontent.com/15974476/207816480-2e3c07d6-4dfa-43c4-aede-86198b60a24d.png)

**Comment by solstice23** [comment]
![image](https://user-images.githubusercontent.com/23134847/207851667-6e3a828c-83b0-49c1-af37-ea0c2be39b3b.png)
