### ISSUE TITLE
无法关闭兼容性检查

### ISSUE THREAD

**Issue by EncoreEureka** [solstice23/refined-now-playing-netease#82]
更新之后重复跳兼容性检查，无法关闭

**Comment by solstice23** [comment]
完成检查后不要点重启，点重载

**Comment by solstice23** [comment]
另外是什么版本的，现在最新的是https://github.com/solstice23/refined-now-playing-netease/releases/tag/2.8.0.1

**Comment by EncoreEureka** [comment]
感谢大佬！！！
