### ISSUE TITLE
底栏颜色未完全覆盖 & 浅色部分元素不易看清

### ISSUE THREAD

**Issue by Skimige** [solstice23/refined-now-playing-netease#87]
![image](https://user-images.githubusercontent.com/9017470/219941649-92797538-d33a-4b4c-ab68-0de39b4cd108.png)

插件列表与之前一致，均为最新版

***

关闭「优化底栏」后浅色则会有部分元素不易看清：

![image](https://user-images.githubusercontent.com/9017470/219941779-09274081-156d-4b50-9a13-b50683cb9f9e.png)

此图使用的例子：https://music.163.com/song?id=29829683

**Comment by solstice23** [comment]
插件列表

**Comment by Skimige** [comment]
> 插件列表

https://github.com/solstice23/refined-now-playing-netease/issues/57

RNP 2.8.2

**Comment by solstice23** [comment]
还有别的插件吗

**Comment by Skimige** [comment]
和之前 issue 里列出的一样，除了插件全部升级到最新版本外没有变化，网易云未升级

**Comment by solstice23** [comment]
ok应该知道原因了 明天看看
