### ISSUE TITLE
进度条加载不正确

### ISSUE THREAD

**Issue by Helpless-Mao** [solstice23/refined-now-playing-netease#88]
进度条加载不正确
![image](https://user-images.githubusercontent.com/123917504/219962916-819a785c-a158-47b2-9261-a4d312cbc3a6.png)
![image](https://user-images.githubusercontent.com/123917504/219962955-8c39779f-2987-4a12-a5db-ed93f72ff62e.png)

**Comment by solstice23** [comment]
material you 设置里关闭不应用正在播放界面开关，如果已经是关的就关闭再打开

**Comment by Helpless-Mao** [comment]
解决辽感谢

**Comment by Helpless-Mao** [comment]
> material you 设置里关闭不应用正在播放界面开关，如果已经是关的就关闭再打开

解决辽感谢
