### ISSUE TITLE
与MaterialYou主体合用时进度条消失

### ISSUE THREAD

**Issue by Oreficus** [solstice23/refined-now-playing-netease#89]
![LRLUH`FQD(2J~@V3%M LUT5](https://user-images.githubusercontent.com/118652957/220854420-1a2b90a5-dc71-4c88-9888-5b96e0422b51.png)
无法拖动进度条

**Comment by solstice23** [comment]
![image](https://user-images.githubusercontent.com/23134847/220857034-8e309b56-8517-4351-9ae3-9e7f3ba03dfc.png)
MD You 设置里关掉这个，不行就打开再关闭
