### ISSUE TITLE
[Bug] 部分歌曲的歌词中空格消失

### ISSUE THREAD

**Issue by EastMonster** [solstice23/refined-now-playing-netease#91]
#### 环境
- NCM 2.10.7
- BetterNCM 1.0.2
- RefinedNowPlaying 2.9.1
已安装的其他插件：
- Material You
- RoundCornerNCM
- FluentProgressBar
- InfLink
- TinyNCM

#### 描述
插件启用时，播放[这首歌](https://music.163.com/song?id=1395957507&userid=349859630)时，歌词间的空格全部消失，但逐字功能正常，不知是否和 #55 一样同为歌词源异常。不安装插件的歌词空格是正常的。

#### 截图
![有插件](https://s2.loli.net/2023/02/24/Havzn2Dm8PwWust.png)
![无插件](https://s2.loli.net/2023/02/24/BlkMOH1Z9f3T5n7.png)

**Comment by solstice23** [comment]
应该是歌词源异常，不过我应该可以将其与原歌词比对来手动修复

**Comment by solstice23** [comment]
已修复
