### ISSUE TITLE
Material You兼容问题

### ISSUE THREAD

**Issue by Lu-Tianxing** [solstice23/refined-now-playing-netease#92]
![G%6I 1GUF{M%5G}MXIZOWMU](https://user-images.githubusercontent.com/73741454/221383448-c2938366-3a40-460a-8ed6-49c4e84ae218.png)
![CZF}QUVMC 68Q$AEPZXFCUK](https://user-images.githubusercontent.com/73741454/221383450-fc4817ad-0be1-4c52-9a87-b28740a0fdfd.png)
![88{(3P0%6~FE(L Z)FY4P62](https://user-images.githubusercontent.com/73741454/221383453-5293c8a2-8c3f-4b1e-a0bc-1c0a0fa6778b.png)
![$5T2QGS$V_P8WSJW1P9YR5](https://user-images.githubusercontent.com/73741454/221383455-211ce70b-3099-4789-9628-68eccf3329f8.png)
如图，在MaterialYou勾选隐藏LOGO后 前进/返回栏（顶部框架左侧边缘）位置改变，导致在正在播放页面中收回按钮错位。
能否在StyleSnippet中添加一个兼容脚本？还是说这个issue我应该投给MaterialYou？

**Comment by Marce1ek** [comment]
遇到了一样的问题👀
