### ISSUE TITLE
”隐藏整个底栏“功能Bug！（这个功能一定要留下来！）

### ISSUE THREAD

**Issue by LinJie-mjyb** [solstice23/refined-now-playing-netease#94]
新加的”隐藏整个底栏“功能很好！超赞！
但是有点小bug，如下：
已开启“不自动隐藏底栏”：https://hakaimg.com/i/2023/02/28/qyk8ql.png

开启”隐藏整个底栏“：https://hakaimg.com/i/2023/02/28/qylk9w.png

但是依然会隐藏整个底栏：https://hakaimg.com/i/2023/02/28/qymu57.png

没有达到”仅在‘不自动隐藏底栏’关闭时生效“的效果，逻辑没问题，效果也很好，就是实现时有点小bug，所以！一定要留下这个功能！！！一定要！留下了！

**Comment by solstice23** [comment]
我做成一个选择组吧，这样可以让设置统一一点

空闲隐藏底栏：关 / 隐藏多余元素 / 隐藏整个底栏

**Comment by solstice23** [comment]
p.s. Github 可以直接粘贴图片到输入框的
