### ISSUE TITLE
【功能建议】播放页沉浸主题色跟随material you动态取色

### ISSUE THREAD

**Issue by MoeToo** [solstice23/refined-now-playing-netease#98]
当前效果：播放页和其他页面元素颜色不统一
![image](https://user-images.githubusercontent.com/61534814/222879768-251be42b-8fa4-4d8a-a4ab-3e417349004f.png)
![image](https://user-images.githubusercontent.com/61534814/222879792-4d77dfe1-4e36-4838-a9cd-ef90813e2fc1.png)

期望效果：内外颜色一致，或者可以跟随其中一个的设置

**Comment by solstice23** [comment]
refined now playing 的取色要稍微不一样一点，以更好的适配播放页面
